In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('../Data/v2_final.tsv',sep='\t')
print(df.head())

   index     city        country  \
0      0      Ada  United States
1      1  Addison  United States
2      2   Adrian  United States
3      3   Adrian  United States
4      4   Albion  United States

                                         description  \
0  Ada witch - Sometimes you can see a misty blue...
1  A little girl was killed suddenly while waitin...
2  If you take Gorman Rd. west towards Sand Creek...
3  In the 1970's, one room, room 211, in the old ...
4  Kappa Delta Sorority - The Kappa Delta Sororit...

                   location     state state_abbrev  longitude   latitude  \
0              Ada Cemetery  Michigan           MI -85.504893  42.962106
1           North Adams Rd.  Michigan           MI -84.381843  41.971425
2             Ghost Trestle  Michigan           MI -84.035656  41.904538
3  Siena Heights University  Michigan           MI -84.017565  41.905712
4            Albion College  Michigan           MI -84.745177  42.244006

   city_longitude  ...  Optional_LATITUDE3 Optional_LATITUDE4  \
0      -85.495480  ...                 NaN                NaN
1      -84.347168  ...                 NaN                NaN
2      -84.037166  ...                 NaN                NaN
3      -84.037166  ...                 NaN                NaN
4      -84.753030  ...                 NaN                NaN

  Optional_LONGITUDE1 Optional_LONGITUDE2 Optional_LONGITUDE3  \
0           -85.50056           -85.49169                 NaN
1                 NaN                 NaN                 NaN
2                 NaN                 NaN                 NaN
3                 NaN                 NaN                 NaN
4                 NaN                 NaN                 NaN

  Optional_LONGITUDE4             Optional_NAME1    Optional_NAME2  \
0                 NaN  Egypt Valley Country Club  Findlay Cemetery
1                 NaN                        NaN               NaN
2                 NaN                        NaN               NaN
3                 NaN                        NaN               NaN
4                 NaN                        NaN               NaN

   Optional_NAME3  Optional_NAME4
0             NaN             NaN
1             NaN             NaN
2             NaN             NaN
3             NaN             NaN
4             NaN             NaN

[5 rows x 64 columns]

/var/folders/0g/wrn8fh3s6x93w1fnwvvh6x4c0000gn/T/ipykernel_96013/1529750582.py:1: DtypeWarning: Columns (63) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../Data/v2_final.tsv',sep='\t')

In [5]:
df.columns

Index(['index', 'city', 'country', 'description', 'location', 'state',
       'state_abbrev', 'longitude', 'latitude', 'city_longitude',
       'city_latitude', 'Audio Evidence', 'Audio Reasoning', 'Witness Count',
       'Witness Reasoning', 'Event', 'apparition_types_str',
       'apparition_adj_str', 'unique_apparition_mentions', 'Murder per capita',
       'Violent Crime per capita', 'Property Crime per capita',
       'Undergrad_Grad_Rate', 'HS_Grad_Rate', 'STEM_Grad_Percentage',
       'Visual Evidence', 'Visual Reasoning', 'death_rate_Alzheimer's disease',
       'death_rate_Cancer', 'death_rate_Heart disease',
       'death_rate_Unintentional injuries', 'death_rate_All causes',
       'death_rate_Influenza and pneumonia', 'death_rate_Suicide',
       'death_rate_Kidney disease', 'death_rate_CLRD', 'death_rate_Diabetes',
       'Haunted Places Date', 'Alcohol Deaths', 'Alcohol Deaths Under 21',
       'State', 'time_of_day', 'Daylight Data USNO Navy',
       'Daylight Data TimeandDate', 'Image Path', 'objects', 'caption',
       'spacy_entities', 'GeoName_Count', 'Geographic_LATITUDE',
       'Geographic_LONGITUDE', 'Geographic_NAME', 'Optional_LATITUDE1',
       'Optional_LATITUDE2', 'Optional_LATITUDE3', 'Optional_LATITUDE4',
       'Optional_LONGITUDE1', 'Optional_LONGITUDE2', 'Optional_LONGITUDE3',
       'Optional_LONGITUDE4', 'Optional_NAME1', 'Optional_NAME2',
       'Optional_NAME3', 'Optional_NAME4'],
      dtype='object')

In [6]:
# Drop NA states and keep the first occurrence of each state
state_agg_df = df.dropna(subset=["state"]).drop_duplicates(subset=["state"])

# Select just the relevant columns: State and a sample crime stat (e.g., Violent Crime per capita)
result_df = state_agg_df[["state",'Murder per capita',
       'Violent Crime per capita', 'Property Crime per capita',
       'Undergrad_Grad_Rate', 'HS_Grad_Rate', 'STEM_Grad_Percentage', 'death_rate_Alzheimer\'s disease',
       'death_rate_Cancer', 'death_rate_Heart disease',
       'death_rate_Unintentional injuries', 'death_rate_All causes',
       'death_rate_Influenza and pneumonia', 'death_rate_Suicide',
       'death_rate_Kidney disease', 'death_rate_CLRD', 'death_rate_Diabetes']]

# Keep only 50 states (some may be non-states like DC or territories)
final_df = result_df.head(50)
print(final_df)

                state  Murder per capita  Violent Crime per capita  \
0            Michigan       1.035219e-05                  0.000602
529      Pennsylvania       1.577098e-05                  0.000551
1063       California       5.398169e-06                  0.000272
1277    Massachusetts       3.711877e-06                  0.000450
2064         Arkansas       2.269685e-05                  0.001428
2118           Oregon       8.137460e-06                  0.000581
2867          Arizona       5.500951e-06                  0.000356
3023         Maryland       4.492784e-05                  0.001672
3193         Oklahoma                NaN                       NaN
3404            Maine                NaN                       NaN
3461           Alaska                NaN                       NaN
3493        Louisiana       4.115381e-05                  0.000736
3592          Alabama                NaN                       NaN
3816             Ohio       1.469178e-05                  0.000483
4293       New Jersey       8.050966e-07                  0.000119
4487     North Dakota                NaN                       NaN
4545          Wyoming       3.147106e-06                  0.000277
4621   North Carolina       8.808069e-06                  0.000453
4622         Kentucky       1.393254e-05                  0.000490
5202           Kansas                NaN                       NaN
5324         New York       4.800467e-06                  0.000429
5527        Wisconsin       2.015765e-05                  0.000044
6057             Iowa                NaN                       NaN
6226    West Virginia                NaN                       NaN
6332       New Mexico       1.379783e-05                  0.000014
6410       Washington       5.823344e-06                  0.000536
6628         Illinois       1.574917e-05                  0.000688
6664          Indiana       1.714542e-05                  0.000827
7351         Virginia       1.043662e-05                  0.000319
7568            Idaho       1.466214e-06                  0.000250
7602    New Hampshire       2.541432e-06                  0.000268
7706          Vermont                NaN                       NaN
7769           Nevada       5.630625e-06                  0.000348
7825           Hawaii       2.121661e-06                  0.000173
7921             Utah       5.759663e-06                  0.000676
8054         Nebraska       3.561005e-06                  0.000376
8165          Georgia       1.982851e-05                  0.000536
8454            Texas       6.640502e-06                  0.000466
8624          Montana                NaN                       NaN
9192        Tennessee       1.488882e-05                  0.000967
9413          Florida       4.983979e-06                  0.000622
9741         Missouri       2.080064e-05                  0.000795
10055        Delaware                NaN                       NaN
10092    South Dakota       3.727888e-06                  0.000460
10167     Mississippi       3.125430e-06                  0.000182
10230     Connecticut       4.879897e-06                  0.000233
10415       Minnesota       5.038436e-06                  0.000382
10577  South Carolina                NaN                       NaN
10746    Rhode Island       3.290419e-06                  0.000227
10814        Colorado       5.909779e-06                  0.000536

       Property Crime per capita Undergrad_Grad_Rate HS_Grad_Rate  \
0                       0.001781               62.0%        84.1%
529                     0.002186               67.0%        86.5%
1063                    0.001479               64.1%        84.5%
1277                    0.001353               73.5%        88.0%
2064                    0.004587               46.9%        87.6%
2118                    0.004292               62.4%        80.0%
2867                    0.002032               26.3%        77.8%
3023                    0.003464               68.3%        86.9%
3193                         NaN               46.3%        84.9%
3404                         NaN               58.1%        87.4%
3461                         NaN               26.4%        80.4%
3493                    0.004087               49.8%        80.1%
3592                         NaN               51.8%        91.7%
3816                    0.001859               58.4%        82.0%
4293                    0.000615               66.3%        90.6%
4487                         NaN               52.1%        88.3%
4545                    0.002952               58.2%        82.1%
4621                    0.002745               61.9%        86.5%
4622                    0.003037               49.2%        90.6%
5202                         NaN               53.4%        87.2%
5324                    0.000826               66.0%        82.8%
5527                    0.000142               63.2%        90.1%
6057                         NaN               68.5%        91.6%
6226                         NaN               47.0%        91.3%
6332                    0.000000               43.6%        75.1%
6410                    0.004521               69.3%        81.1%
6628                    0.002276               61.5%        86.2%
6664                    0.002955               61.1%        87.2%
7351                    0.002181               67.0%        87.5%
7568                    0.001061               47.4%        80.8%
7602                    0.001465               67.7%        88.4%
7706                         NaN               67.1%        84.5%
7769                    0.002073               45.1%        84.1%
7825                    0.002145               53.3%        85.2%
7921                    0.005132               54.5%        87.4%
8054                    0.002515               60.7%        88.4%
8165                    0.003350               42.6%        82.0%
8454                    0.002440               54.9%        90.0%
8624                         NaN               47.3%        86.6%
9192                    0.003459               50.7%        90.5%
9413                    0.006685               56.1%        87.2%
9741                    0.003239               56.5%        89.7%
10055                        NaN               65.3%        89.0%
10092                   0.002679               51.5%        84.1%
10167                   0.002428               51.9%        85.0%
10230                   0.001663               68.0%        88.5%
10415                   0.002442               64.9%        83.7%
10577                        NaN               61.9%        81.1%
10746                   0.001598               71.1%        83.9%
10814                   0.003105               54.1%        81.1%

      STEM_Grad_Percentage  death_rate_Alzheimer's disease  death_rate_Cancer  \
0                    22.0%                       23.994737         184.521053
529                  21.0%                       19.242105         185.647368
1063                 23.0%                       26.673684         160.668421
1277                 22.0%                       20.321053         177.678947
2064                 22.0%                       26.626316         197.426316
2118                 19.0%                       29.315789         177.626316
2867                 13.0%                       31.442105         157.289474
3023                 30.0%                       16.915789         179.942105
3193                 21.0%                       26.242105         193.326316
3404                 20.0%                       28.473684         191.010526
3461                 23.0%                       21.700000         177.005263
3493                 19.0%                       32.394737         202.589474
3592                 21.0%                       31.315789         194.773684
3816                 21.0%                       26.747368         192.457895
4293                 25.0%                       17.673684         176.178947
4487                 22.0%                       34.200000         164.905263
4545                 34.0%                       24.863158         165.184211
4621                 23.0%                       29.157895         182.836842
4622                 18.0%                       29.589474         210.157895
5202                 19.0%                       23.410526         175.836842
5324                 19.0%                       10.142105         168.036842
5527                 21.0%                       24.100000         175.657895
6057                 20.0%                       27.478947         176.105263
6226                 18.0%                       24.263158         202.789474
6332                 23.0%                       18.936842         155.952632
6410                 23.0%                       40.984211         173.942105
6628                 19.0%                       20.957895         185.078947
6664                 22.0%                       27.026316         193.226316
7351                 22.0%                       22.736842         179.963158
7568                 22.0%                       26.878947         164.831579
7602                 21.0%                       25.384211         179.800000
7706                 17.0%                       29.310526         177.673684
7769                 16.0%                       18.305263         180.889474
7825                 17.0%                       13.394737         144.057895
7921                 26.0%                       24.394737         134.521053
8054                 18.0%                       23.342105         170.742105
8165                 22.0%                       29.115789         181.010526
8454                 25.0%                       27.378947         171.005263
8624                 25.0%                       22.415789         170.773684
9192                 16.0%                       34.105263         198.326316
9413                 19.0%                       18.100000         169.010526
9741                 19.0%                       24.831579         189.484211
10055                21.0%                       20.147368         188.510526
10092                27.0%                       29.831579         172.305263
10167                19.0%                       29.657895         204.421053
10230                22.0%                       16.352632         166.657895
10415                16.0%                       23.684211         168.115789
10577                21.0%                       33.552632         188.400000
10746                18.0%                       22.100000         180.700000
10814                25.0%                       28.900000         152.752632

       death_rate_Heart disease  death_rate_Unintentional injuries  \
0                    228.531579                          37.631579
529                  211.652632                          43.515789
1063                 185.468421                          29.715789
1277                 169.084211                          30.489474
2064                 241.636842                          48.721053
2118                 158.105263                          40.000000
2867                 170.231579                          49.242105
3023                 202.884211                          27.126316
3193                 260.036842                          56.310526
3404                 176.242105                          42.631579
3461                 161.205263                          56.878947
3493                 242.521053                          51.789474
3592                 254.447368                          50.952632
3816                 218.263158                          43.084211
4293                 202.573684                          29.831579
4487                 172.273684                          40.226316
4545                 181.494737                          56.905263
4621                 196.505263                          46.068421
4622                 238.547368                          57.184211
5202                 184.331579                          42.573684
5324                 227.452632                          26.357895
5527                 183.136842                          43.594737
6057                 188.336842                          37.763158
6226                 239.010526                          63.415789
6332                 169.773684                          64.568421
6410                 166.136842                          38.842105
6628                 204.642105                          34.052632
6664                 214.915789                          41.031579
7351                 189.105263                          36.294737
7568                 174.547368                          45.305263
7602                 179.831579                          39.752632
7706                 176.189474                          43.684211
7769                 220.321053                          42.800000
7825                 155.431579                          30.931579
7921                 162.763158                          38.542105
8054                 172.700000                          37.152632
8165                 216.073684                          42.615789
8454                 204.873684                          39.189474
8624                 170.578947                          54.857895
9192                 236.957895                          52.989474
9413                 183.368421                          44.015789
9741                 227.342105                          48.363158
10055                203.752632                          40.057895
10092                178.457895                          47.300000
10167                277.131579                          58.710526
10230                175.942105                          36.178947
10415                137.410526                          38.021053
10577                208.194737                          50.847368
10746                196.357895                          37.784211
10814                150.621053                          45.163158

       death_rate_All causes  death_rate_Influenza and pneumonia  \
0                 821.400000                           17.089474
529               810.089474                           16.684211
1063              691.131579                           19.936842
1277              722.563158                           20.884211
2064              920.400000                           23.800000
2118              761.252632                           12.536842
2867              732.915789                           16.652632
3023              783.526316                           19.010526
3193              936.815789                           21.189474
3404              789.342105                           16.889474
3461              774.273684                           14.200000
3493              943.936842                           20.426316
3592              962.257895                           21.178947
3816              855.515789                           17.300000
4293              737.215789                           15.342105
4487              721.205263                           16.836842
4545              793.100000                           22.431579
4621              841.873684                           20.484211
4622              942.815789                           23.110526
5202              794.221053                           19.552632
5324              708.447368                           22.515789
5527              748.678947                           16.757895
6057              745.315789                           19.057895
6226              963.210526                           20.594737
6332              779.294737                           17.484211
6410              730.684211                           13.147368
6628              785.400000                           19.457895
6664              858.273684                           17.542105
7351              786.089474                           19.063158
7568              758.642105                           16.736842
7602              739.789474                           15.368421
7706              740.321053                           12.257895
7769              836.531579                           21.115789
7825              623.805263                           19.621053
7921              734.936842                           19.921053
8054              750.915789                           16.473684
8165              874.536842                           20.642105
8454              803.152632                           17.184211
8624              786.100000                           16.805263
9192              924.336842                           24.963158
9413              726.594737                           11.305263
9741              853.800000                           20.931579
10055             799.710526                           16.468421
10092             742.900000                           19.068421
10167             987.678947                           23.778947
10230             696.263158                           16.778947
10415             687.115789                           12.615789
10577             885.236842                           17.521053
10746             748.347368                           17.431579
10814             718.694737                           15.668421

       death_rate_Suicide  death_rate_Kidney disease  death_rate_CLRD  \
0               11.773684                  15.136842        44.742105
529             12.031579                  17.805263        38.757895
1063             9.889474                   7.821053        38.647368
1277             7.636842                  16.442105        35.031579
2064            15.410526                  19.900000        54.178947
2118            16.094737                   8.052632        45.263158
2867            16.678947                   8.384211        45.157895
3023             8.963158                  12.589474        35.315789
3193            16.378947                  14.552632        60.747368
3404            13.900000                  14.542105        49.747368
3461            21.889474                  10.568421        43.378947
3493            12.268421                  24.884211        42.810526
3592            13.273684                  20.957895        52.510526
3816            11.773684                  14.989474        49.842105
4293             7.094737                  15.978947        31.636842
4487            14.605263                   9.889474        37.963158
4545            21.700000                  11.384211        59.610526
4621            12.268421                  17.594737        46.526316
4622            14.473684                  20.673684        60.978947
5202            14.157895                  17.000000        49.810526
5324             7.115789                  10.852632        32.021053
5527            12.684211                  14.347368        39.352632
6057            12.184211                   7.452632        46.352632
6226            15.457895                  19.884211        61.531579
6332            20.047368                  12.300000        46.631579
6410            13.789474                   6.278947        43.526316
6628             9.215789                  18.147368        39.373684
6664            12.994737                  19.378947        53.926316
7351            11.805263                  18.310526        39.510526
7568            17.900000                   9.189474        47.831579
7602            13.236842                  11.126316        45.063158
7706            14.415789                   6.684211        46.157895
7769            19.415789                  17.778947        56.100000
7825            11.473684                  11.236842        19.510526

In [7]:
# Save to CSV
final_df.to_csv("../Data/agg_stats_by_state.csv", index=False)

final_df.head()

,state,Murder per capita,Violent Crime per capita,Property Crime per capita,Undergrad_Grad_Rate,HS_Grad_Rate,STEM_Grad_Percentage,death_rate_Alzheimer's disease,death_rate_Cancer,death_rate_Heart disease,death_rate_Unintentional injuries,death_rate_All causes,death_rate_Influenza and pneumonia,death_rate_Suicide,death_rate_Kidney disease,death_rate_CLRD,death_rate_Diabetes
0,Michigan,0.000010,0.000602,0.001781,62.0%,84.1%,22.0%,23.994737,184.521053,228.531579,37.631579,821.400000,17.089474,11.773684,15.136842,44.742105,25.236842
529,Pennsylvania,0.000016,0.000551,0.002186,67.0%,86.5%,21.0%,19.242105,185.647368,211.652632,43.515789,810.089474,16.684211,12.031579,17.805263,38.757895,22.652632
1063,California,0.000005,0.000272,0.001479,64.1%,84.5%,23.0%,26.673684,160.668421,185.468421,29.715789,691.131579,19.936842,9.889474,7.821053,38.647368,21.568421
1277,Massachusetts,0.000004,0.000450,0.001353,73.5%,88.0%,22.0%,20.321053,177.678947,169.084211,30.489474,722.563158,20.884211,7.636842,16.442105,35.031579,16.521053
2064,Arkansas,0.000023,0.001428,0.004587,46.9%,87.6%,22.0%,26.626316,197.426316,241.636842,48.721053,920.400000,23.800000,15.410526,19.900000,54.178947,26.547368

In [10]:
final_df.describe()

,Murder per capita,Violent Crime per capita,Property Crime per capita,death_rate_Alzheimer's disease,death_rate_Cancer,death_rate_Heart disease,death_rate_Unintentional injuries,death_rate_All causes,death_rate_Influenza and pneumonia,death_rate_Suicide,death_rate_Kidney disease,death_rate_CLRD,death_rate_Diabetes
count,3.800000e+01,38.000000,38.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,1.055632e-05,0.000495,0.002549,25.162211,178.236105,196.947895,43.621263,797.213158,18.276316,13.590526,14.114947,45.030000,23.298000
std,9.886444e-06,0.000332,0.001372,5.784643,15.291783,31.274786,9.084333,84.082557,3.141106,3.589351,4.504294,8.488271,3.983802
min,8.050966e-07,0.000014,0.000000,10.142105,134.521053,137.410526,26.357895,623.805263,11.305263,7.094737,6.278947,19.510526,15.236842
25%,3.996033e-06,0.000273,0.001693,21.800000,169.443421,173.161842,37.843421,737.859211,16.697368,11.509211,10.773684,39.357895,21.294737
50%,5.866562e-06,0.000456,0.002434,25.123684,177.676316,188.721053,42.715789,784.463158,17.531579,13.115789,13.750000,45.210526,22.686842
75%,1.483956e-05,0.000597,0.003205,29.147368,188.482895,217.715789,49.111842,850.818421,20.567105,15.446053,17.732895,49.972368,25.577632
max,4.492784e-05,0.001672,0.006685,40.984211,210.157895,277.131579,64.568421,987.678947,24.963158,21.889474,24.884211,61.531579,34.484211

In [11]:
# Save as JSON
final_df.to_json("../Source/react-ui/public/apparitionMap/agg_stats_data.json", orient="records", indent=2)